{{- if .Values.job.enabled }}
apiVersion: apps/v1
kind: Job
metadata:
  name: {{ include "generic-app.fullname" . }}
  labels:
    {{- include "generic-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "generic-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.job.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "generic-app.labels" . | nindent 8 }}
        {{- with .Values.job.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: {{ .Values.job.restartPolicy }}
      {{- with .Values.job.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "generic-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.job.podSecurityContext | nindent 8 }}

      {{- if .Values.job.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.job.securityContext | nindent 12 }}
          image: "{{ .Values.job.image.registry }}/{{ .Values.job.image.repository }}:{{ .Values.job.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.job.image.pullPolicy }}
          {{- with .Values.job.containerCommand }}
          command: 
            {{- toYaml . | nindent 12}}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.job.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml .Values.job.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.job.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml .Values.job.readinessProbe | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.job.resources | nindent 12 }}
          {{- with .Values.job.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.job.env }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.job.envFrom }}
          envFrom:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.job.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.job.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
